[package]
name = "celly-demo"
version = "0.1.0"
authors = ["Dmitry Shlagoff <wessmoke@gmail.com>"]

[dependencies]
ws = "0.5"

celly = "0.5"
iron = "0.3.0"
logger = "0.0.3"

serde = "0.7"
serde_macros = "0.7"

rmp-serde = "0.9"
